// src/Clean Moodle/settingspage/logged-out.svelte
<script lang="ts">
	import {createEventDispatcher} from 'svelte';

	import {getUsername} from '../../shared/moodle-functions-v3/credentials.js';

	const dispatch = createEventDispatcher<{
		login: {
			username: string;
			password: string;
		};
	}>();

	let username: string = getUsername() ?? '';
	let password = '';

	function onSubmit() {
		if (username && password) {
			dispatch('login', {
				username,
				password,
			});
		}
	}
</script>

<form on:submit|preventDefault={onSubmit}>
	<div class="replace-flex-input">
		<h5>Login</h5>
		<input placeholder="Username" bind:value={username} />
		<input bind:value={password} placeholder="Password" type="password" />
		<button class="btn-save" type="submit"> Login </button>
	</div>
</form>

// src/Timetable v5/components/logged-out.tsx
import {h, JSX} from 'preact';
import {useRef} from 'preact/hooks';

import {getUsername} from '../../shared/moodle-functions-v3/credentials';

const LoggedOut = ({
	loggedOut,
	cb,
}: {
	loggedOut: boolean;
	cb: (creds: {username: string; password: string}) => void;
}) => {
	const usernameRef = useRef<HTMLInputElement>(null);
	const passwordRef = useRef<HTMLInputElement>(null);

	if (!loggedOut) {
		return null;
	}

	const handleLoginClick: JSX.GenericEventHandler<HTMLFormElement> = event => {
		event.preventDefault();

		const username = usernameRef.current?.value.trim();
		const password = passwordRef.current?.value;

		if (username !== undefined && password !== undefined) {
			cb({
				username,
				password,
			});
		}
	};

	return (
		<div class="login-popup">
			<form onSubmit={handleLoginClick}>
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Login</h5>
						<input
							ref={usernameRef}
							required
							placeholder="Username"
							class="input-group-text"
							defaultValue={getUsername()}
						/>
						<input
							ref={passwordRef}
							required
							placeholder="Password"
							class="input-group-text"
							type="password"
						/>
					</div>
					<button type="submit" class="btn btn-primary">
						Login
					</button>
				</div>
			</form>
		</div>
	);
};

export default LoggedOut;
